### ISSUE TITLE
generic solution

### ISSUE THREAD

**Issue by tj** [segment-boneyard/go-start-nsq#1]
might be nicer to have a mongroup-ish solution for osx since launchd sucks, and upstart is too verbose for dev IMO, something like:

``` yaml
logs: /var/log

vars:
  data: --data-path /tmp/nsqd
  lookup: --lookupd-tcp-address :4160

redshift:
  start:
    - nsq
    - red-range
    - red-extract
    - red-buffer
    - red-transform
    - red-load

nsq:
  start:
    - nsqd-1
    - nsqd-2
    - nsqd-3
    - nsqlookupd
    - nsqadmin

nsqd-1:
  exec: nsqd --tcp-address :5001 {lookup} {data}

nsqd-2:
  exec: nsqd --tcp-address :5002 {lookup} {data}

nsqd-3:
  exec: nsqd --tcp-address :5003  {lookup} {data}

nsqlookupd:
  exec: nsqlookupd

nsqadmin:
  exec: nsqadmin --lookupd-http-address :4161

...
```
